CREATE DATABASE IF NOT EXISTS capstone CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE capstone;

CREATE TABLE IF NOT EXISTS members (
  id INT AUTO_INCREMENT PRIMARY KEY, 
  username VARCHAR(10) NOT NULL UNIQUE, 
  password VARCHAR(10) NOT NULL, 
  best_time DECIMAL(8, 4) DEFAULT NULL
);